### ISSUE TITLE
This browser or app might not be secure

### ISSUE THREAD

**Issue by Soossie** [Venipa/ytmdesktop2#9]
I'm not able to log in to my google account because the login screen prompts that this browser isn't secure. Is this known?

**Comment by Happypat900** [comment]
i tried a second tiem and it worked 🤔

**Comment by Soossie** [comment]
Could it be a regional issue? I tried to run it as an administrator as well but same issue.

> i tried a second time and it worked 🤔

**Comment by Venipa** [comment]
ye thanks to google they're actively preventing 3rd party apps to sign in with old browsers or invalid browsers.

For now you'll have to just press "try again" or reload the sign in page which should resolve it

https://user-images.githubusercontent.com/17952364/154026771-64ceccde-5dc2-4bb7-877f-7b6f7e8a8e66.mp4

**Comment by Soossie** [comment]
Thanks, that worked!

**Comment by simonbcn** [comment]
> For now you'll have to just press "try again" or reload the sign in page which should resolve it

```
macOS 14
ytmdesktop2 v0.10.11
```

For me this doesn't solve the problem.

> ye thanks to google they're actively preventing 3rd party apps to sign in with old browsers or invalid browsers.

This is a security issue and it is fine for them to do so. There are other third party apps that work properly.

**Comment by blinkertoon** [comment]
I'm still getting this issue. Can't you surely just update the browser you use (which would in theory also be more secure as Google says)? Thanks.

**Comment by EfeDevirgen** [comment]
for me it didnt solve it but i brute forced it(tried again and again) and it worked after a chapta

**Comment by 1600kHz** [comment]
I don't understand either. It's more of a bot prevention thing I think. Had to retry four times. What browser is the app using under the hood if not Chromium, Firefox..?
